### PR TITLE
Add reboot and ap_mode API support

### PR DESCRIPTION
**Pull request by davidjb**
This adds Python API support for these actions as per the API docs at https://raw.githubusercontent.com/OpenGarage/OpenGarage-Firmware/master/docs/OGAPI1.1.0.pdf. My use case is for these actions to eventually end up as switches within Home Assistant so it's possible to easily restart the OG and trigger a reconfigure its wifi from HA.

### CODE REVIEW

**Review by Danielhiversen — APPROVED** [review]
Thanks

**Comment by davidjb** [comment]
Thanks @Danielhiversen! 

Would you mind creating a release on PyPI for updating Home Assistant's requirements?  Thank you in advance.

**Comment by Danielhiversen** [comment]
Done

**Comment by davidjb** [comment]
Thanks heaps!

**Pull request merged**
